services:
  - type: web
    name: web-site
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: BP_CPYTHON_VERSION
        value: 3.12.*
